server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: aaaa
    password: aaaa
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huiDragon81/cloud-config-repo.git

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh