server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huiDragon81/cloud-config-repo.git

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans